#!/bin/bash
docker build -t $IMAGE_NAME \
    --build-arg PHP_VERSION=$PHP_VERSION \
    --build-arg APP_ENV=$APP_ENV \
    --build-arg SERVICE_TYPE=$SERVICE_TYPE \
    --build-arg CORS_ALLOWED_METHODS=$CORS_ALLOWED_METHODS \
    --build-arg CORS_ALLOWED_HEADERS=$CORS_ALLOWED_HEADERS \
    .
