#!/bin/bash
docker build -t $DOCKER_REPO:cli \
    --build-arg APP_ENV=production \
    --build-arg SERVICE_TYPE=cli \
    .

docker build -t $DOCKER_REPO:cli-dev \
    --build-arg APP_ENV=dev \
    --build-arg SERVICE_TYPE=cli
    .



docker build -t $DOCKER_REPO:fpm \
    --build-arg APP_ENV=production \
    --build-arg SERVICE_TYPE=fpm \
    .

docker build -t $DOCKER_REPO:fpm-dev \
    --build-arg APP_ENV=dev \
    --build-arg SERVICE_TYPE=fpm \
    .



docker build -t $IMAGE_NAME:fpm-nginx \
    --build-arg APP_ENV=production \
    --build-arg SERVICE_TYPE=fpm-nginx \
    .

docker build -t $IMAGE_NAME:fpm-nginx-dev \
    --build-arg APP_ENV=dev \
    --build-arg SERVICE_TYPE=fpm-nginx \
    .
