#!/bin/bash
docker push -t $DOCKER_REPO:cli
docker push -t $DOCKER_REPO:cli-dev

docker push -t $DOCKER_REPO:fpm
docker push -t $DOCKER_REPO:fpm-dev

docker push -t $DOCKER_REPO:fpm-nginx
docker push -t $DOCKER_REPO:fpm-nginx-dev
